version: "3.8"
services:
  bot:
    image: ghcr.io/${GITHUB_REPOSITORY}:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .env:/app/.env
    depends_on:
      - redis
      - mongo

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

  mongo:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

volumes:
  redis_data:
  mongo_data:
