name: HeimdallWhitelist
version: 1.0.0
main: com.heimdall.whitelist.HeimdallWhitelistPlugin
api-version: 1.16
description: Dynamic whitelist integration with Heimdall Discord bot
author: Heimdall Team
website: https://github.com/lerndmina/Heimdall

commands:
  hwl:
    description: Heimdall Whitelist commands
    usage: /hwl <reload|status|test>
    permission: heimdall.admin
    aliases: [heimdallwhitelist]

permissions:
  heimdall.admin:
    description: Admin commands for Heimdall Whitelist
    default: op
  heimdall.bypass:
    description: Bypass whitelist checks
    default: op
