name: Promote Docker Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version/Tag to promote to latest (e.g., sha-abc123, nightly)"
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/heimdall

jobs:
  promote:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull and retag image
        run: |
          # Pull the specified version
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.version }}
          # Tag it as latest
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.version }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          # Push the latest tag
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
